### PR TITLE
fix test name outputted

### LINKED ISSUE #10: When showing test names, the title is listed as '../My Test Name'
- [X] The [readme](https://github.com/PrismarineJS/prismarine-template/README.md) doesn't contain a resolution to my issue 
- [X] The [example](https://github.com/PrismarineJS/prismarine-template/example.js) doesn't contain a resolution to my issue 

## Versions
 - node: 14.16.1
 - mineflayer-test-api: 1.0.1

## Detailed description of a problem
When showing the names of tests in the console, the test paths are generated incorrectly. For example, with a test file named `myTest.js` containing the test `Jump Forward`, the test name will be rendered as `../Jump Forward`. This is incorrect.

## Your current code
```js
const { registerTest } = require('mineflayer-test-api')

registerTest('Jump Forward', async (server, startPos) => {
  throw new Error('Failed!')
}
```

## Expected behavior
The correct test name should be shown as `test/myTest.js/Jump Forward`

## Additional context
N/A

### PR DESCRIPTION
**Pull request by u9g**
closes https://github.com/PrismarineJS/mineflayer-test-api/issues/10

### CODE REVIEW

File: src/mineflayerTest.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ let testList = []
 let currentDir = ''
```
Comment (TheDudeFromCI) [inline src/mineflayerTest.js]: Looks like the test is failing because this variable is unused. It can be safely removed.

**Review by TheDudeFromCI — CHANGES_REQUESTED** [review]

File: src/mineflayerTest.js (hunk 1 above)
Comment (u9g) [reply src/mineflayerTest.js]: fixed
